"""empty message

Revision ID: 069b40c02453
Revises: 5e11ef8f5d2e
Create Date: 2020-01-17 19:50:10.395138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069b40c02453'
down_revision = '5e11ef8f5d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contribution', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contribution', 'is_approved')
    # ### end Alembic commands ###
