"""empty message

Revision ID: 14b5add53c85
Revises: 367080ecc7d9
Create Date: 2020-01-06 22:57:00.471260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b5add53c85'
down_revision = '367080ecc7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('amount_gross', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'amount_gross')
    # ### end Alembic commands ###
