"""empty message

Revision ID: 20b86105c106
Revises: 14b5add53c85
Create Date: 2020-01-09 00:20:43.899497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b86105c106'
down_revision = '14b5add53c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'is_approved')
    # ### end Alembic commands ###
