"""empty message

Revision ID: 367080ecc7d9
Revises: b846613b404e
Create Date: 2020-01-06 21:54:03.281401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367080ecc7d9'
down_revision = 'b846613b404e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('terms', sa.Integer(), nullable=True))
    op.drop_column('loan', 'term')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('loan', 'terms')
    # ### end Alembic commands ###
