"""empty message

Revision ID: 3fd2116b1781
Revises: 48e02b95dbb2
Create Date: 2020-01-05 04:11:48.496775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd2116b1781'
down_revision = '48e02b95dbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower', sa.Column('code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'borrower', ['code'])
    op.add_column('member', sa.Column('code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'member', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'code')
    op.drop_constraint(None, 'borrower', type_='unique')
    op.drop_column('borrower', 'code')
    # ### end Alembic commands ###
