"""empty message

Revision ID: 48e02b95dbb2
Revises: ae1fb11fabb5
Create Date: 2020-01-05 02:35:41.129778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e02b95dbb2'
down_revision = 'ae1fb11fabb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sequence', ['name'])
    op.create_unique_constraint(None, 'sequence', ['prefix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sequence', type_='unique')
    op.drop_constraint(None, 'sequence', type_='unique')
    # ### end Alembic commands ###
