"""empty message

Revision ID: 4e9ea003bbd3
Revises: 069b40c02453
Create Date: 2020-01-20 00:46:38.485022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9ea003bbd3'
down_revision = '069b40c02453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('created_by', sa.String(length=20), nullable=True))
    op.add_column('member', sa.Column('search_tag', sa.String(length=100), nullable=True))
    op.add_column('member', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('updated_by', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'updated_by')
    op.drop_column('member', 'updated_at')
    op.drop_column('member', 'search_tag')
    op.drop_column('member', 'created_by')
    op.drop_column('member', 'created_at')
    # ### end Alembic commands ###
