"""empty message

Revision ID: 5e11ef8f5d2e
Revises: 20b86105c106
Create Date: 2020-01-12 13:58:58.848865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e11ef8f5d2e'
down_revision = '20b86105c106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_detail', sa.Column('amount_base', sa.Float(), nullable=True))
    op.add_column('loan_detail', sa.Column('amount_interest', sa.Float(), nullable=True))
    op.add_column('loan_detail', sa.Column('term', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_detail', 'term')
    op.drop_column('loan_detail', 'amount_interest')
    op.drop_column('loan_detail', 'amount_base')
    # ### end Alembic commands ###
